name: iscir_forms_app
description: ISCIR Forms Management App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.2

  # File handling
  path_provider: ^2.1.1
  share_plus: ^7.2.1

  # Navigation
  go_router: ^15.1.2

  # PDF Generation
  pdf: ^3.10.4
  printing: ^5.11.0

  # Image processing
  image: ^4.1.3

  minio: ^3.5.8
  http: ^1.1.0
  crypto: ^3.0.3

  connectivity_plus: ^6.0.0

  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3

  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # Excel export
  excel: ^4.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

  # Future: We'll add assets here for the PDF templates
  assets:
   - assets/templates/
  #   - assets/images/