// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0KiKuZk_yRLba7h6KhsEoYo7iQxnZvg',
    appId: '1:214033176425:web:7e0ed80ef2adb6bdac4ff8',
    messagingSenderId: '214033176425',
    projectId: 'iscir-forms-auth',
    authDomain: 'iscir-forms-auth.firebaseapp.com',
    storageBucket: 'iscir-forms-auth.firebasestorage.app',
    measurementId: 'G-R68YYBDPRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmKLwENPgj7G8hKP6XTz7Pz9N2Rypf5I',
    appId: '1:214033176425:android:a4fe3250ea030243ac4ff8',
    messagingSenderId: '214033176425',
    projectId: 'iscir-forms-auth',
    storageBucket: 'iscir-forms-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArDGyJeEP-nMHS4HqPE49m5gJS1gVPjl8',
    appId: '1:214033176425:ios:2fe7a702afefb347ac4ff8',
    messagingSenderId: '214033176425',
    projectId: 'iscir-forms-auth',
    storageBucket: 'iscir-forms-auth.firebasestorage.app',
    iosBundleId: 'com.example.iscirFormsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArDGyJeEP-nMHS4HqPE49m5gJS1gVPjl8',
    appId: '1:214033176425:ios:2fe7a702afefb347ac4ff8',
    messagingSenderId: '214033176425',
    projectId: 'iscir-forms-auth',
    storageBucket: 'iscir-forms-auth.firebasestorage.app',
    iosBundleId: 'com.example.iscirFormsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-0KiKuZk_yRLba7h6KhsEoYo7iQxnZvg',
    appId: '1:214033176425:web:2c315ab58fa7b78eac4ff8',
    messagingSenderId: '214033176425',
    projectId: 'iscir-forms-auth',
    authDomain: 'iscir-forms-auth.firebaseapp.com',
    storageBucket: 'iscir-forms-auth.firebasestorage.app',
    measurementId: 'G-R9PG5LZ5BT',
  );

}